# **Chapter 3: Controlling Program Flow**

- Topic:
  - Tìm hiểu về câu lệnh có điều kiện **Conditional statements (`if, elif, else`)**
  - Tìm hiểu về **Match Case Statement - v3.10**
  - Hiểu về cách dùng vòng lặp **loops `while, for`**
  - Cách sử dụng `break` và `continue` trong vòng lặp

## **#1: Making Decisions: The `if` Statement**

- Trong lập trình, rất thường xuyên chúng ta muốn một đoạn code chỉ chạy khi thỏa mãn một điều kiện nào đó. Giống như trong đời thực: “Nếu trời mưa thì mình mang ô”, chương trình cũng cần cách để “quyết định” dựa trên tình huống. Công cụ cơ bản nhất của Python để làm việc này chính là câu lệnh `if`.

- Câu lệnh `if` cho phép bạn chạy một khối code có điều kiện. Nó sẽ kiểm tra xem một điều kiện nào đó có đúng `(True)` hay không. Nếu đúng thì khối code bên trong if sẽ được thực hiện. Nếu sai `(False)` thì khối code đó bị bỏ qua hoàn toàn, chương trình nhảy xuống phần tiếp theo.

### **The Structure of an `if` Statement**

- Cú pháp cơ bản như sau:

```python
if condition:
    # Code to execute if the condition is True
    statement1
    statement2
    # ... more statements ...

# Code here runs regardless of the condition, after the if block
next_statement
```

- Ở đoạn code trên:

    1.  **`if` Keyword**: Câu lệnh bắt đầu bằng từ khóa `if`.
    2. **condition**: Đây là một biểu thức trả về `True` hoặc `False`. Thường dùng **comparison operators `(==, !=, <, >, <=, >=)`** hoặc **logical operators `(and, or, not)`** mà ta đã học trước đó. Bạn cũng có thể dùng trực tiếp một biến boolean.
    3. **Colon `:`**: Phải có dấu `:` ở cuối dòng điều kiện. Nó báo hiệu phần khối code phụ thuộc sắp bắt đầu.
    4. **Khối lệnh thụt lề (Indented Block)**: Các dòng ngay sau dòng `if`, và thụt vào trong (thường là 4 khoảng trắng), tạo thành khối lệnh của `if`. Python dùng thụt lề để xác định khối lệnh nào thuộc về đâu. Dòng đầu tiên không còn thụt lề nữa là kết thúc khối `if`.


In [ ]:
age = 20

print("Checking voting eligibility...")

if age >= 18:
    print("You are old enough to vote.")
    print("Please register if you haven't already.")

print("Eligibility check complete.")

Checking voting eligibility...
You are old enough to vote.
Please register if you haven't already.
Eligibility check complete.


### **The Importance of Indentation**

- Trong Python, thụt lề không chỉ để code đẹp mà là một phần của cú pháp. Nó quyết định lệnh nào thuộc khối `if`. Nếu thụt lề sai sẽ gây lỗi hoặc hành vi không mong muốn.

In [ ]:
# Correct indentation
temperature = 30
if temperature > 25:
    print("It's a warm day.") # Indented correctly
    print("Wear light clothes.") # Indented correctly

# Incorrect indentation (will cause an IndentationError)
# if temperature > 25:
# print("It's a warm day.") # Missing indentation

- Luôn dùng thụt lề nhất quán, thường là 4 khoảng trắng mỗi cấp. Hầu hết các phần mềm viết code sẽ tự động giúp bạn làm việc này đúng cách.

### **Visualizing the Flow**

<p align="center">
  <img src="../images/basic_if_flowchart.svg" alt="basic_if_flowchart"/>
  <br/>
  <p align="center">
    Flowchart cho thấy con đường thực thi của một câu lệnh <code>if</code>. Nếu điều kiện đánh giá đúng, khối mã <code>if</code> sẽ được thực thi trước khi tiếp tục. Nếu sai, khối <code>if</code> sẽ bị bỏ qua.
  <p>
</p>


## **#2: Handling Alternatives: `elif` and `else`**

- Câu lệnh `if` giúp chương trình chỉ chạy một đoạn code khi điều kiện là `True`. Nhưng thực tế, chúng ta thường cần kiểm tra nhiều trường hợp hoặc có một hành động mặc định khi các điều kiện trước đều `False`. Để làm được điều này, Python cung cấp thêm hai phần mở rộng: `elif` và `else`.

### **Checking Multiple Conditions with `elif`**

- Giả sử bạn muốn phân loại một số là dương, âm hay bằng zero – rõ ràng cần kiểm tra nhiều khả năng. `elif` (viết tắt của `else if`) cho phép bạn thêm các điều kiện phụ, và chúng chỉ được kiểm tra khi các điều kiện trước đó đều `False`.

- Bạn có thể nối nhiều `elif` sau `if`. Python sẽ kiểm tra từng điều kiện từ trên xuống dưới. Ngay khi gặp điều kiện đầu tiên `True`, nó sẽ thực hiện khối lệnh tương ứng và bỏ qua hoàn toàn phần còn lại của toàn bộ cấu trúc `if-elif-else`.

- Cấu trúc tổng quát: như sau:

```python
if condition_1:
    # Block 1: Executes if condition_1 is True
    statement(s)
elif condition_2:
    # Block 2: Executes if condition_1 is False AND condition_2 is True
    statement(s)
elif condition_3:
    # Block 3: Executes if condition_1 AND condition_2 are False,
    # AND condition_3 is True
    statement(s)
# ... you can have more elif blocks

In [ ]:
number = -10

if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")

# If number is 0, neither condition above is True, so nothing happens yet.

- number > 0 → `False` → bỏ qua khối đầu.
- number < 0 → `True` → in `The number is negative.` và kết thúc toàn bộ cấu trúc.

Còn nếu number = 0? Cả hai điều kiện trên đều sai → không có gì được in ra. Để xử lý trường hợp “còn lại”, chúng ta dùng `else`.

### **The Default Case: `else`**

- Phần else là khối lệnh chạy chỉ khi tất cả các điều kiện if và elif phía trên đều sai. Nó giống như một “lưới bắt hết” (catch-all). else không cần điều kiện và luôn phải đặt cuối cùng.

- Cấu trúc tổng quát như sau:

```python
if condition_1:
    # Block 1: Executes if condition_1 is True
    statement(s)
elif condition_2:
    # Block 2: Executes if condition_1 is False AND condition_2 is True
    statement(s)
# ... more elif blocks (optional) ...
else:
    # Block N: Executes if ALL preceding conditions (condition_1, condition_2, ...) are False
    statement(s)

In [ ]:
number = 0

print(f"Checking the number: {number}")

if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    # This block runs only if number is not > 0 AND number is not < 0
    print("The number is zero.")

print("Finished checking.")

<p align="center">
  <img src="../images/if_elif_else_flowchart.png" alt="if_elif_else_flowchart"/>
  <br/>
  <p align="center">
    Flowchart thể hiện quy trình ra quyết định để phân loại một số là <code>positive</code>, <code>negative</code> hoặc bằng <code>0</code> bằng cách sử dụng <code>if-elif-else</code>.
  <p>
</p>

### **Order and Exclusivity**

Hai điều quan trọng cần nhớ về `if-elif-else`:

1.  **Thứ tự rất quan trọng (Order Matters)**: Các điều kiện được kiểm tra từ trên xuống. Nếu có nhiều điều kiện cùng đúng, chỉ khối đầu tiên đúng được thực hiện.

In [ ]:
score = 85

if score >= 70: # This is True first
    grade = 'C'
elif score >= 80: # This is also True, but checked later
    grade = 'B'
else:
    grade = 'Not C or B'

print(grade) # Output: C

Để đúng, phải đặt điều kiện khắt khe (điểm cao) lên trước:

In [ ]:
score = 85

if score >= 90:
    grade = 'A'
elif score >= 80: # Checked second, True for 85
    grade = 'B'
elif score >= 70: # Checked third
    grade = 'C'
# ... other grades
else:
    grade = 'F'

print(grade) # Output: B

2. **Chỉ một khối duy nhất được chạy (Only One Block Executes)**: Trong một chuỗi `if-elif-else`, tối đa chỉ một khối được thực hiện. Một khi đã tìm thấy điều kiện đúng, Python bỏ qua hết phần còn lại. Khối `else` chỉ chạy khi không có điều kiện nào đúng.

## **#3: Match Case Statement**

- Từ Python 3.10 trở đi, Python có thêm một cấu trúc mới rất mạnh mẽ gọi là **match-case (structural pattern matching)**. Nó giúp chúng ta viết các câu lệnh điều kiện một cách rõ ràng, đẹp mắt và linh hoạt hơn rất nhiều so với chuỗi `if-elif-else` dài dòng.

- Thay vì phải dùng nhiều `if-elif`, `match-case` cho phép bạn “so khớp” giá trị với các mẫu `pattern` khác nhau một cách trực quan.

- Cấu trúc tổng quát: như sau:
    
    - **Match subject**: Giá trị hoặc **variable** cần kiểm tra.
    - **case pattern**: Một `pattern` khớp với `subject`
    - **_ (Wildcard)**: Một `default catch-all pattern`,tương tự như "mặc định" trong các câu lệnh `switch` của các ngôn ngữ khác.
    

```python
match subject:
    case pattern1:
        # Code block if pattern1 matches
    case pattern2:
        # Code block if pattern2 matches
    case _:
        # Default case (wildcard) if no other pattern matches

### **Match Case Statements with Constants**

- Matching constants là một trong những cách sử dụng đơn giản nhất của câu lệnh `match-case`. Nó kiểm tra xem một biến có khớp với các giá trị hằng số cụ thể hay không và cho phép các hành động khác nhau dựa trên hằng số phù hợp.

In [ ]:
name = input(input("Enter your name: "))
match name:
    case "A":
        print("Hello, A!")
    case "B":
        print("Hello, B!")
    case _:
        print("Hello, stranger!")

Hello, B!


- Nếu `person` có giá trị đúng là chuỗi `A` → in `Hello, A!`.
- Nếu là `person` là `B` → in `Hello, B!`.
- Nếu là bất kỳ giá trị nào khác (ví dụ "C", 123, True…) → chạy case `_` và in `Hello, stranger!`.

### **Match Case Statements with OR Operator**

- Câu lệnh `match-case` cũng có thể được sử dụng với **logical operators** như hoặc để kết hợp nhiều **patterns**. Điều này cho phép một hệ thống khớp linh hoạt hơn, nơi bạn có thể nhóm các **patterns** và kiểm tra kết quả phù hợp với bất kỳ **patterns** nào trong số chúng.

In [ ]:
num = input(input("Enter a number: "))
match num:
    case 10 | 20 | 30:  # Matches 10, 20, or 30
        print(f"Matched: {num}")
    case _:
        print("No match found")

Enter a number: 10
10
No match found


- Nếu `num` khớp với `pattern 10 | 20 | 30` sử dụng toán tử `or` với bất kỳ giá trị nào trong ba giá trị này -> `print(f"Matched: {num}")`
- Nếu `num` không khớp với bất kỳ giá trị nào, ký tự đại diện `_` -> `print("No match found")`

### **Match Case Statement with Python `If Condition`**

- Chúng ta cũng có thể thêm `if condition`  sau một trường hợp để tạo ra khả năng kiểm soát chi tiết hơn đối với quá trình đối sánh. Điều này cho phép chúng tôi thêm các kiểm tra bổ sung trong một trường hợp.

In [ ]:
score = 85
subject = "History"

match subject:
    # Matches "History" or "Geography" AND checks if score is >= 80
    case "History" | "Geography" if score >= 80:
        print(f"Excellent in Social Studies with a score of {score}!")
    case "Math" if score >= 90:
        print("Excellent in Math!")
    case _:
        print(f"Needs improvement in {subject}.")

Excellent in Social Studies with a score of 85!


### **Match Case Statement on Sequences**


In [ ]:
point = [-2, 9]
match point:
    case [0, 0]:
        print("Origin")
    case [x, y]:
        print("Point is", x, y)
    case [x]:
        print("Point is", x)
    case _:
        print("Other")

Point is -2 9


In [ ]:
point = [-2, 9]
match point:
    case [0, 0]:
        print("Origin")
    case [x, y] if x > 0 and y > 0:
        print("Point is", x, y)
    case [x]:
        print("Point is", x)
    case _:
        print("Other")

Other


In [ ]:
lines = [1, 99, 7]
match lines:
    case [x]:
        print("One line")
    case [x, y]:
        print("Two lines")
    case [int() | float() as x, int() | float() as y]:
        print("Point is", x, y)
    case [x, y, z] if x + y > z and x + z > y and y + z > x:
        print("A triangle")
    case [x, y, z]:
        print("Three lines")
    case _:
        print("Other")


Three lines


### **Match Case Statement on Mappings (Dictionaries)**

- **Mappings (Dictionaries)** là **data type** phổ biến khác trong Python và `match-case` có thể được sử dụng để so khớp với **Dictionaries**, kiểm tra các `keys` và `values`.

In [ ]:
person = {
    "name": "Alice",
    "age": 25
}
match person:
  	# Dictionary with name and age keys
    case {"name": name, "age": age}:
        print(f"Name: {name}, Age: {age}")

    # Dictionary with only name key
    case {"name": name}:
        print(f"Name: {name}")
    case _:
        print("Unknown format")

Name: Alice, Age: 25


### **Match Case Statement with Python Class**

In [ ]:
class Shape:
    pass

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
    __match_args__ = ("radius",)

class Rectangle(Shape):
    def __init__(self, width, height):
        self.width = width
        self.height = height
    __match_args__ = ("width", "height")

def check_shape(shape):
    match shape:

      	# Match Circle and extract the radius
        case Circle(radius):
            print(f"circle radius {radius}.")

        # Match Rectangle and extract width and height
        case Rectangle(width, height):
            print(f"Rectangle width {width} and height {height}.")

        # Default case for any other object
        case _:
            print("This is an unknown shape.")

# Create objects of Circle and Rectangle
circle = Circle(10)
rectangle = Rectangle(4, 6)

# Test with different shapes
check_shape(circle)
check_shape(rectangle)

circle radius 10.
Rectangle width 4 and height 6.


## **#4: Repeating Actions: The while Loop**

- Đôi khi, bạn muốn một đoạn code lặp đi lặp lại nhiều lần miễn là một điều kiện nào đó còn `True`. Vòng lặp `while` của Python chính là công cụ dành riêng cho việc này. Nó đặc biệt hữu ích khi bạn không biết trước cần lặp bao nhiêu lần.

- Hãy tưởng tượng như bạn nói Python: "Cứ làm việc này mãi cho đến khi điều kiện này không còn đúng nữa"

### **The Structure of a `while` Loop**

- Cú pháp cơ bản như sau:

```python
while condition:
    # Code block to be executed repeatedly
    # This block MUST be indented
    statement1
    statement2
    # ... potentially update variables affecting the condition ...
```

- **`while` keyword**: Báo hiệu bắt đầu vòng lặp.
- `condition`: Là một biểu thức trả về `True` hoặc `False` (giống như điều kiện trong if).
- **Colon `:`**: Kết thúc `condition` của `while`
- **Indented Code Block**:
    - Tất cả các lệnh thụt vào bên trong thuộc về vòng lặp. Khối này sẽ được chạy đi chạy lại.
    - Rất quan trọng: phải có lệnh nào đó bên trong khối này cuối cùng làm cho `condition` trở thành `False`, nếu không bị lỗi vòng lặp vô tận!

### **How Python Executes a `while` Loop**

- Quy trình rất đơn giản của `while` loop:
    
    1. **Check the Condition**: Python kiểm tra `condition` trước tiên.
    2. **Execute or Skip**:
        - Nếu `condition`: `True` -> PYthon sẽ chạy toàn bộ **indented code block**.
        - Nếu `condition`: `False` -> Python bỏ qua toàn **indented code block** và nhảy xuống phần code sau vòng lặp.
    3. **Repeat**: Nếu vừa chạy khối lệnh (Vì `conditon`: `True`), Python sẽ quay lại **Check the Condition** lần nữa, đến khi `conditon`: `False`.

In [1]:
# Initialize a counter variable BEFORE the loop
count = 1

# The loop continues as long as 'count' is less than 5
while count < 5:
    print(f"Current count is: {count}")
    # IMPORTANT: Update the counter inside the loop!
    count = count + 1 # Or use the shorthand: count += 1

print("Loop finished!")

Current count is: 1
Current count is: 2
Current count is: 3
Current count is: 4
Loop finished!


- Có 3 yếu tố quan trọng để điều khiển được vòng lặp này:
    - **Initialization**: `count = 1` – chuẩn bị giá trị ban đầu trước khi vào vòng lặp.
    - **Condition**: `count < 5` - dược kiểm tra trước mỗi lần lặp.
    - **Update**: `count = count + 1` - thay đổi **`count` variable** ảnh hưởng đến điều kiện bên trong vòng lặp. Nếu quên bước này, `count` mãi là `1` → điều kiện luôn `True` → vòng lặp không bao giờ dừng!

<p align="center">
  <img src="../images/while_flowchart.png" alt="while_flowchart"/>
  <br/>
  <p align="center">
    Flowchart minh họa logic thực thi của vòng lặp <code>while</code>.
  <p>
</p>

### **The Danger: Infinite Loops**

- Nếu điều kiện trong `while` không bao giờ thành `False`, `while` sẽ chạy mãi mãi. Đây là lỗi rất hay gặp của người mới.

In [3]:
# WARNING: This creates an infinite loop!
# counter = 0
# while counter >= 0:
    # print(f"Counter is {counter}. Still positive!")
    # Oops! We forgot to change 'counter' in a way
    # that makes the condition (counter >= 0) false.
    # Maybe we meant to decrement it? Or check a different condition?
    # Without a change, it will run forever.
    # counter = counter + 1 # This actually makes it *more* likely to stay >= 0!

- Nếu lỡ chạy code có vòng lặp vô tận, bạn có thể dừng bằng cách nhấn **Ctrl + C** trong terminal.

### **Example: Waiting for Specific User Input**

- `while` rất mạnh khi cần lặp cho đến khi xảy ra một sự kiện nào đó – ví dụ chờ người dùng gõ `quit` để thoát.



In [ ]:
# Initialize response to something that ensures the loop runs at least once
response = ""

# Keep asking until the user types 'quit'
while response.lower() != 'quit':
    response = input("Enter some text (or type 'quit' to exit): ")
    print(f"You entered: {response}")

print("Okay, quitting now. Goodbye!")

- Với tư cách là lập trình viên, ta sẽ không biết người dùng sẽ nhập bao nhiêu trước khi gõ “quit”.
- `while` xử lý hoàn hảo sự không chắc chắn này: cứ hỏi mãi cho đến khi điều kiện response.lower() != 'quit' thành `False`.

## **#5: Iterating Over Sequences: The for Loop**

- `for` loop một công cụ rất hiệu quả để thực hiện một hành động cho từng phần tử trong một **string** hoặc tập hợp dữ liệu. Nó đặc biệt hữu ích khi bạn đã biết trước mình cần xử lý từng mục một trong một `list`, chuỗi ký tự, v.v...

### **Basic `for` Loop Syntax**

- Cấu trúc cơ bản như sau:

```python
for variable_name in sequence:
    # Code block to execute for each item
    # Use variable_name to access the current item
    statement1
    statement2
    # ...
```
- `for`: Từ khóa bắt đầu vòng lặp
- `variable_name`: Tên variable bạn đặt (nên sử dụng 1 tên dễ hiểu). **Variable** này sẽ lần lượt nhận giá trị của từng phần tử của `sequance` trong mỗi lần lặp.
- `in`: Từ khóa nối `variable_name` với `sequance`
- `sequance`: Tập hợp các phần tử mà bạn muốn duyệt qua. Nó có thể là `list`, chuỗi ký tự (string), hoặc các kiểu dữ liệu khác thuộc **mutable**.
- **Colon`:`**: Kết thúc dòng lệnh `for`.
- **Indented Code Block**: Giống như `if` và `while`.

### **Iterating Over Lists**

- `List` là tập hợp có thứ tự, rất phù hợp để dùng với vòng lặp `for`. Giả sử bạn có danh sách nhiệt độ và muốn in từng giá trị.

In [4]:
temperatures = [19.5, 22.1, 18.0, 25.3]

print("Daily temperatures:")
for temp in temperatures:
    print(f"Temperature recorded: {temp}°C")

print("\nLoop finished.")

Daily temperatures:
Temperature recorded: 19.5°C
Temperature recorded: 22.1°C
Temperature recorded: 18.0°C
Temperature recorded: 25.3°C

Loop finished.


- `temperatures` là chuỗi dữ liệu (list).
- `temp`: biến lặp.
- Lần 1: `temp = 19.5` → in ra dòng đầu tiên.
- Lần 2: `temp = 22.1` → in ra dòng thứ hai.
- … cho đến phần tử cuối cùng.
- Sau khi hết `list`, vòng lặp dừng và chạy tiếp lệnh không thụt lề.

### **Iterating Over Strings**
- **Strings** cũng là một dãy các ký tự, nên `for` có thể duyệt từng ký tự một cách tự động.

In [5]:
user_name = "Alice"

print(f"Characters in the name {user_name}:")
for character in user_name:
    print(f"- {character}")

Characters in the name Alice:
- A
- l
- i
- c
- e


### **Repeating Code a Specific Number of Times with `range()`**

- Đôi khi bạn không có `list` hay `string`, mà chỉ muốn lặp đúng một số lần cố định.

- `range()` của Python sinh ra một dãy số để for duyệt qua:
    1. `range(stop)`: Tạo dãy số từ `0` đến `stop-1`.
        ```python
        print("Counting from 0 to 4:")
        for i in range(5): # Generates 0, 1, 2, 3, 4
            print(i)
        ```
        - Lưu ý: `range(5)` cho ta 5 con số từ `0`. Và **`i` variable** thường được nhiều lập trình viên đặt để thể hiện `(index)`, bạn có thể thay đổi một tên cho biến này khác.
    2. `range(start, stop)`: Từ `start` đến `stop-1`.
        ```python
        print("\nNumbers from 2 to 5:")
        for num in range(2, 6): # Generates 2, 3, 4, 5
            print(num)
        ```
    3. `range(start, stop, step)`: Tăng dần theo bước `step`.
        ```python
        print("\nOdd numbers less than 10:")
        for odd_num in range(1, 10, 2): # Generates 1, 3, 5, 7, 9
            print(odd_num)
        ```

### **Practical Example: Summing List Elements**


- Hãy thử kệt hợp `for` với những gì chúng ta đã học qua **(variables, operators)** để tính tổng điểm trong một `list`

In [7]:
scores = [88, 92, 75, 98, 85]
total_score = 0 # Initialize accumulator variable

for score in scores:
    total_score = total_score + score # Add current score to total

print(f"The list of scores is: {scores}")
print(f"The total score is: {total_score}")

The list of scores is: [88, 92, 75, 98, 85]
The total score is: 438


`total_score` variable bắt đầu từ `0`, mỗi lần lặp cộng thêm một điểm từ `list → cuối cùng in ra tổng.

### **When to Use `for` vs `while`**
- `for`:
    1. Bạn muốn duyệt từng phần tử trong một chuỗi đã biết `(list, string, range…)`.
    2. Bạn cần lặp đúng một số lần cố định.
    3. `for` tự động quản lý việc lấy phần tử tiếp theo và dừng đúng lúc → code ngắn gọn, dễ đọc.

- `while`:
1. Bạn lặp cho đến khi một `condition` nào đó `True/False`, và không biết trước sẽ lặp bao nhiêu lần.
2. Bạn phải tự quản lý điều kiện dừng bên trong vòng lặp.

## **#6: Controlling Loops: break and continue**

- `for` và `while` đã giúp chúng ta lặp lại code rất mạnh mẽ, nhưng đôi khi bạn cần kiểm soát chi tiết hơn:
    - Muốn dừng hẳn vòng lặp giữa chừng, hoặc bỏ qua phần còn lại của lần lặp hiện tại để sang lần lặp tiếp theo.
    - Python cung cấp đúng hai câu lệnh cho hai nhu cầu này: `break` và `continue`.

### **Exiting Early: The `break` Statement**

- `break` sẽ kết thúc ngay lập tức vòng lặp đang chạy (dù là `for` hay `while`). Khi Python gặp `break`, nó nhảy ra khỏi vòng lặp và chạy tiếp phần code ngay sau vòng lặp.

- Rất hữu ích khi bạn đang tìm kiếm thứ gì đó và muốn dừng ngay khi tìm thấy, hoặc khi gặp lỗi khiến việc tiếp tục lặp trở nên vô nghĩa.

- VD: Tìm vị trí đầu tiên của một số trong list.

In [8]:
numbers = [1, 5, 12, 8, 9, 21, 5, 3]
target = 9
found_at_index = -1 # Initialize with a value indicating not found

print(f"Searching for {target} in {numbers}...")

for index, num in enumerate(numbers):
    print(f"Checking index {index}: value {num}")
    if num == target:
        found_at_index = index
        print(f"Found {target}!")
        break # Exit the loop immediately

# Code here runs after the loop finishes or breaks
if found_at_index != -1:
    print(f"Target {target} first found at index {found_at_index}.")
else:
    print(f"Target {target} not found in the list.")

print("Search complete.")

Searching for 9 in [1, 5, 12, 8, 9, 21, 5, 3]...
Checking index 0: value 1
Checking index 1: value 5
Checking index 2: value 12
Checking index 3: value 8
Checking index 4: value 9
Found 9!
Target 9 first found at index 4.
Search complete.


- Vòng lặp dừng ngay ở `index 4`. Các số `21, 5, 3` không hề được kiểm tra vì `break` đã đưa chương trình ra khỏi vòng lặp ngay lập tức.

<p align="center">
  <img src="../images/break-statement-flow-diagram.png" alt="break-statement-flow-diagram"/>
  <br/>
</p>

### **Skipping an Iteration: The `continue` Statement**

- Khác với `break`, `continue` không dừng hẳn vòng lặp mà chỉ bỏ qua phần code còn lại của lần lặp hiện tại và nhảy ngay sang lần lặp tiếp theo:
    - Với vòng lặp `while`: quay lại kiểm tra `condition`.
    - Với vòng lặp `for`: lấy phần tử tiếp theo trong `sequance`.
- Rất tiện khi bạn gặp dữ liệu muốn bỏ qua (ví dụ: số âm, giá trị không hợp lệ) nhưng vẫn muốn xử lý các phần tử sau.

- VD: Tính tổng chỉ các số dương trong `list`

In [9]:
data = [10, -5, 20, 0, -15, 30, 5]
positive_sum = 0

print(f"Processing data: {data}")

for num in data:
    print(f"Current number: {num}")
    if num <= 0:
        print("  Skipping non-positive number.")
        continue # Skip the rest of this iteration
    # This code only runs if continue was NOT executed
    print(f"  Adding {num} to sum.")
    positive_sum += num

print(f"\nSum of positive numbers: {positive_sum}")

Processing data: [10, -5, 20, 0, -15, 30, 5]
Current number: 10
  Adding 10 to sum.
Current number: -5
  Skipping non-positive number.
Current number: 20
  Adding 20 to sum.
Current number: 0
  Skipping non-positive number.
Current number: -15
  Skipping non-positive number.
Current number: 30
  Adding 30 to sum.
Current number: 5
  Adding 5 to sum.

Sum of positive numbers: 65


<p align="center">
  <img src="../images/continue-statement-flow-diagram.png" alt="continue-statement-flow-diagram"/>
  <br/>
</p>

### **`break` vs `continue`**

- `break`: Thoát hẳn khỏi vòng lặp → chạy code sau vòng lặp.
- `continue`: Bỏ qua phần còn lại của lần lặp hiện tại → sang lần lặp tiếp theo ngay.

### **Nested Loops**

- Nếu có vòng lặp bên trong vòng lặp lồng nhau **(nesting)**, `break` và continue chỉ ảnh hưởng đến vòng lặp gần nhất (vòng lặp bên trong).

In [10]:
for i in range(1, 4): # Outer loop
    print(f"Outer loop iteration {i}:")
    for j in ['a', 'b', 'c', 'STOP', 'd']: # Inner loop
        if j == 'STOP':
            print("  Inner loop breaking!")
            break # Breaks only the inner loop
        if j == 'b':
            print(f"  Skipping '{j}' in inner loop...")
            continue # Continues to next item in inner loop
        print(f"  Processing inner item: {j}")
    # This line is reached after the inner loop completes or breaks
    print(f"Outer loop iteration {i} finished.")
print("All loops complete.")

Outer loop iteration 1:
  Processing inner item: a
  Skipping 'b' in inner loop...
  Processing inner item: c
  Inner loop breaking!
Outer loop iteration 1 finished.
Outer loop iteration 2:
  Processing inner item: a
  Skipping 'b' in inner loop...
  Processing inner item: c
  Inner loop breaking!
Outer loop iteration 2 finished.
Outer loop iteration 3:
  Processing inner item: a
  Skipping 'b' in inner loop...
  Processing inner item: c
  Inner loop breaking!
Outer loop iteration 3 finished.
All loops complete.


Hãy để ý:
- `break` chỉ dừng việc xử lý `['a', 'b', 'c', 'STOP', 'd']` và vòng lặp bên ngoài vẫn tiếp tục các vòng lặp của nó.
- Tương tự, `continue` chỉ bỏ qua việc in `'b'` trong mỗi lần chạy vòng lặp bên trong.

## **#7: Nested Control Structures**

- Python sử dụng `if, elif, else` để thực hiện code có điều kiện, và dùng `while` hay `for` để lặp lại hành động. Khi kết hợp chúng với nhau, khả năng của chương trình tăng lên rất nhiều. Một cách kết hợp mạnh mẽ là lồng nhau **(nesting)**: đặt một cấu trúc điều khiển luồng bên trong cấu trúc khác. Nhờ đó, bạn có thể xây dựng những logic phức tạp hơn.

- Hãy tưởng tượng: bạn cần kiểm tra nhiều điều kiện phụ thuộc lẫn nhau, hoặc cần thực hiện một công việc lặp lại cho từng phần tử trong một vòng lặp khác. Nesting chính là giải pháp.

### **Nested Conditional Statements**

- Bạn có thể đặt `if, elif, else` bên trong một khối `if/elif/else` khác. Nhờ vậy, các điều kiện phụ chỉ được kiểm tra khi điều kiện chính đã thỏa mãn.

- VD: Kiểm tra một người có được giảm giá đặc biệt không – phải là học sinh, có thẻ hợp lệ và dưới 25 tuổi.

In [11]:
is_student = True
has_valid_id = False
age = 20

print("Checking discount eligibility...")

if age < 25: # Outer condition: Age check
    print("Age requirement met.")
    if is_student: # Inner condition 1: Student status
        print("Student status confirmed.")
        if has_valid_id: # Inner condition 2: ID check
            print("Valid ID confirmed.")
            print("Congratulations! You are eligible for the discount.")
        else: # Inner else (belongs to ID check)
            print("Valid ID not found. Discount not applicable.")
    else: # Inner else (belongs to student status check)
        print("Not a student. Discount not applicable.")
else: # Outer else (belongs to age check)
    print("Age requirement not met. Discount not applicable.")

print("Eligibility check complete.")

Checking discount eligibility...
Age requirement met.
Student status confirmed.
Valid ID not found. Discount not applicable.
Eligibility check complete.


- Quan sát thụt lề: các khối bên trong thụt sâu hơn khối ngoài. Python dùng thụt lề để biết lệnh nào thuộc khối nào. Các kiểm tra học sinh và thẻ chỉ chạy khi `age < 25` đúng.

### **Nested Loops**
Vòng lặp cũng có thể Nesting. Thường dùng để xử lý dữ liệu nhiều chiều `(như table, grids)` hoặc tạo tổ hợp từ nhiều chuỗi.

#### **Nested `for` Loops**

- Giả sử bạn muốn in tất cả các tọa độ `(x, y)` trên `3x2 gird` (`x` từ `0` đến `2`, `y` từ `0` đến `1`).

In [12]:
print("Generating grid coordinates:")

# Outer loop iterates through x values
for x in range(3): # x will be 0, 1, 2
    # Inner loop iterates through y values for EACH x
    for y in range(2): # y will be 0, 1
        print(f"  ({x}, {y})") # Print the coordinate pair

print("Coordinate generation finished.")

Generating grid coordinates:
  (0, 0)
  (0, 1)
  (1, 0)
  (1, 1)
  (2, 0)
  (2, 1)
Coordinate generation finished.


#### **Nested while Loops**

- Bạn cũng có thể lồng `while`, nhưng phải cẩn thận quản lý điều kiện để tránh vòng lặp vô tận.

In [13]:
outer_count = 0
print("Outer loop starting...")
while outer_count < 2:
    print(f"Outer loop iteration {outer_count}")
    inner_count = 0
    # Inner loop runs while inner_count < 3
    while inner_count < 3:
        print(f"  Inner loop iteration {inner_count}")
        inner_count += 1 # Important: update inner loop variable
    outer_count += 1 # Important: update outer loop variable
print("Outer loop finished.")

Outer loop starting...
Outer loop iteration 0
  Inner loop iteration 0
  Inner loop iteration 1
  Inner loop iteration 2
Outer loop iteration 1
  Inner loop iteration 0
  Inner loop iteration 1
  Inner loop iteration 2
Outer loop finished.


### **Combining Loops and Conditionals**

#### **`if` Statements Inside Loops**
- Duyệt từng phần tử và chỉ thực hiện hành động khi phần tử đó thỏa điều kiện.

- VD: In ra chỉ các số chẵn trong danh sách.

In [14]:
numbers = [11, 22, 37, 44, 58, 61, 76]
print("Even numbers found:")

for num in numbers:
    # Check the condition for each number in the list
    if num % 2 == 0: # Is the number divisible by 2?
        print(f"  {num}")

print("Search complete.")

Even numbers found:
  22
  44
  58
  76
Search complete.


- Vòng lặp `for` duyệt từng số, còn `if` bên trong quyết định có in ra hay không.

#### **Loops Inside if Statements**

- Bạn có thể muốn thực thi một vòng lặp chỉ nếu một điều kiện nhất định là đúng.

In [15]:
data = ["apple", "banana", "cherry"]
# data = [] # Try uncommenting this line to see the difference

if data: # Checks if the list is not empty (non-empty lists are True-like)
    print("Processing data items:")
    for item in data:
        print(f"  - {item}")
else:
    print("No data items to process.")

Processing data items:
  - apple
  - banana
  - cherry


### **The Importance of Indentation**

- Python dùng thụt lề để xác định khối lệnh nào thuộc về đâu. Khi Nesting, mỗi cấp phải thụt sâu thêm (thường 4 khoảng trắng). Sai thụt lề sẽ gây lỗi `IndentationError` hoặc code chạy sai logic.

In [ ]:
# Correct Indentation
for i in range(2):
    print(f"Outer {i}")
    if i == 0:
        print("  Inner check for i=0") # Indented under if
    for j in range(2):
        print(f"    Inner loop {j}") # Indented under inner for

# Incorrect Indentation (will likely cause errors or wrong logic)
# for i in range(2):
# print(f"Outer {i}") # Error: Expected an indented block
# if i == 0:
# print("  Inner check for i=0")
# for j in range(2):
# print(f"    Inner loop {j}") # Error or wrong scope

### **Keeping Nesting Readable**

- Nesting rất mạnh, nhưng nếu lồng quá sâu (4-5 cấp) code sẽ rất khó đọc và dễ mắc lỗi. Hãy cố gắng giữ ở mức 2-3 cấp là tối đa. Nếu cần sâu hơn, hãy nghĩ đến việc tách logic thành các hàm nhỏ riêng biệt